### ISSUE TITLE
生成文件名的时候LPCWSTR变量赋值好像会报错

### ISSUE THREAD

**Issue by biggwatermelon** [onlyet/WebViewClient#1]
// 创建 dmp 文件
    TCHAR szFileName[MAX_PATH] = { 0 };
    const QString path = QString("%1/%2-%3.dmp").arg(dirpath).arg(qApp->applicationName())
                             .arg(QDateTime::currentDateTime().toString("yyyyMMdd-HHmmss"));
    path.toWCharArray(szFileName);

    HANDLE hDumpFile = CreateFile(szFileName, GENERIC_READ | GENERIC_WRITE,
                                  FILE_SHARE_WRITE | FILE_SHARE_READ, 0, CREATE_ALWAYS, 0, 0);

这块在qt4.8.6编译不过去是为什么

**Comment by onlyet** [comment]
报错信息呢
